### ISSUE TITLE
99% Of my YubNub.dev Is Broken

### ISSUE THREAD

**Issue by IGitSylvia** [JonathanAquino/yubnub#3]
Hi Jonathan,

Is this project active? It should! 

I am quite interested in yubnub, however I can't get your current setup working on my dev machine. I can only get the home page to appear, but to my frustration everything else is broken. Did you forget to include an htaccess or *.conf? 

I would highly appreciate it if you can provide some at least "minimal" installation documentation, otherwise development contributions from eager people (like me...) will hurt what yubnub can be. :)

Thanks!

Sylvia

**Comment by JonathanAquino** [comment]
Hi Sylvia,
It has been a few years since I set up Yubnub, so I guess I've mostly forgotten how I did it. If you can figure it out and send me the instructions, I can add that to the Readme. It's basically just PHP code with a MySQL database.
Jon

**Comment by Wikinaut** [comment]
+1 . I am also interested in having installation instructions available in this repo.

**Comment by JonathanAquino** [comment]
I added some installation instructions to the Readme. Let me know if that fixes your Yubnub installation.
