### ISSUE TITLE
yubnub/public/

### ISSUE THREAD

**Issue by dittoslash** [JonathanAquino/yubnub#4]
Warning: require_once(/home/henry/www/yubnub/app/controllers/HController.php): failed to open stream: No such file or directory in /home/henry/www/yubnub/app/helpers/Autoloader.php on line 22

Fatal error: require_once(): Failed opening required '/home/henry/www/yubnub/app/controllers/HController.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/henry/www/yubnub/app/helpers/Autoloader.php on line 22

**Comment by JonathanAquino** [comment]
I need to get some more information.

Could you try inserting this at the top of app/helpers/Autoloader.php and let me know what it prints out when the error happens:

echo "Autoloading $className <br>\n";
$e = new\Exception(); echo '<pre>' . $e->getTraceAsString();

**Comment by dittoslash** [comment]
Autoloading 
#0 /home/henry/www/yubnub/public/index.php(6): require_once()
#1 {main}

Warning:  require_once(/home/henry/www/yubnub/app/controllers/HController.php): failed to open stream: No such file or directory in /home/henry/www/yubnub/app/helpers/Autoloader.php on line 25



Fatal error:  require_once(): Failed opening required '/home/henry/www/yubnub/app/controllers/HController.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/henry/www/yubnub/app/helpers/Autoloader.php on line 25

**Comment by dittoslash** [comment]
Upon inspection of Github's copy and my copy neither seem to have HController.

**Comment by JonathanAquino** [comment]
Hm - equally strange is the fact that "HController" is not mentioned anywhere in the codebase.

**Comment by JonathanAquino** [comment]
Also it's weird - I would have expected the output to say "Autoloading HController", but it just says "Autoloading ".
